server:
    mode: debug
    host: 0.0.0.0
    port: 8090
    pprof: true
    pprofPort: 6060
    metrics: true
    online: true #true表示本地找不到，去hfNetLoc地址查找并下载模型数据，false表示本地如果没有，直接返回没有
    repos: ./repos
    hfNetLoc: hf-mirror.com   # huggingface.co     hf-mirror.com
    hfScheme: https

scheduler:
    mode: cluster    #运行的两种模式：standalone&cluster,default:standalone
    instanceId: mas-online
    addr: 127.0.0.1:9091
    heartbeatPeriod: 5
    batchSaveNum: 5

download:
    blockSize: 8388608           #默认文件块大小为8MB（8388608），单位字节，1048576（1MB）
    reqTimeout: 0                #远端请求超时时间，单位秒，默认为0，不超时。
    respChunkSize: 8192          #默认对响应结果的读取大小8192，单位字节。
    respChanSize: 30             #响应队列大小
    remoteFileBufferSize: 8388608  #每个分区文件的结果Queue的缓存大小，即当前文件下载时，缓存8MB的数据
    remoteFileRangeSize: 0    #按照这个长度分块下载，0为不切分,测试选项：8388608（8M），67108864（64M），134217728（128M）,536870912(512M),1GB（1073741824）
    remoteFileRangeWaitTime: 0   #每个分区文件下载任务提交时间间隔，单位（ms）。
    goroutineMaxNumPerFile: 8    #远程下载任务启动的最大协程数量


cache:
    enabled: false               #是否启用缓存
    type: 1                     # 采用哪种组件缓存，可选项0(map), 1(Ristretto)
    collectTimePeriod: 5        #定期检测内存使用量时间周期，单位秒（S）
    prefetchMemoryUsedThreshold: 90  #当内存使用量达到该值，将不会预读取，不缓存数据块
    prefetchBlocks: 16           #离线下载时，预先读取块的数量
    prefetchBlockTTL: 30         #离线下载时，预先读取块的存活时间，单位秒（S）

retry:
    delay: 1       #重试间隔时间，单位秒，默认为1
    attempts: 3    #重试次数，默认为3

log:
    maxSize: 20      # 日志文件最大的尺寸（MB）
    maxBackups: 10  #保留旧文件的最大个数
    maxAge: 90      #保留旧文件的最大天数

tokenBucketLimit:
    handlerCapacity: 50   #提交处理任务的超时时间

diskClean:
    enabled: true
    cacheSizeLimit: 41781441855488  #38T
    cacheCleanStrategy: "LRU"  #LRU,FIFO,LARGE_FIRST
    collectTimePeriod: 1  #定期检测磁盘使用量时间周期，单位小时（H）

