// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dingo-hfmirror/internal/dao"
	"dingo-hfmirror/internal/handler"
	"dingo-hfmirror/internal/router"
	"dingo-hfmirror/internal/server"
	"dingo-hfmirror/internal/service"
	"dingo-hfmirror/pkg/app"
	"dingo-hfmirror/pkg/config"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func wireApp(configConfig *config.Config) (*app.App, func(), error) {
	echo := server.NewEngine()
	fileDao := dao.NewFileDao()
	fileService := service.NewFileService(fileDao)
	sysService := service.NewSysService()
	fileHandler := handler.NewFileHandler(fileService, sysService)
	metaDao := dao.NewMetaDao(fileDao)
	metaService := service.NewMetaService(fileDao, metaDao)
	metaHandler := handler.NewMetaHandler(metaService)
	sysHandler := handler.NewSysHandler(sysService)
	httpRouter := router.NewHttpRouter(echo, fileHandler, metaHandler, sysHandler)
	httpServer := server.NewServer(configConfig, echo, httpRouter)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}
