// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.0--rc1
// source: manager.proto

package manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SchedulerFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      string                 `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Etag          string                 `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	InstanceId    string                 `protobuf:"bytes,6,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	StartPos      int64                  `protobuf:"varint,7,opt,name=startPos,proto3" json:"startPos,omitempty"`
	EndPos        int64                  `protobuf:"varint,8,opt,name=endPos,proto3" json:"endPos,omitempty"`
	FileSize      int64                  `protobuf:"varint,9,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerFileRequest) Reset() {
	*x = SchedulerFileRequest{}
	mi := &file_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerFileRequest) ProtoMessage() {}

func (x *SchedulerFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerFileRequest.ProtoReflect.Descriptor instead.
func (*SchedulerFileRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{3}
}

func (x *SchedulerFileRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SchedulerFileRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *SchedulerFileRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SchedulerFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchedulerFileRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *SchedulerFileRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SchedulerFileRequest) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *SchedulerFileRequest) GetEndPos() int64 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *SchedulerFileRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// 注册响应
type SchedulerFileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchedulerType    int32                  `protobuf:"varint,1,opt,name=schedulerType,proto3" json:"schedulerType,omitempty"`
	ProcessId        int64                  `protobuf:"varint,2,opt,name=processId,proto3" json:"processId,omitempty"`
	Host             string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port             int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	MasterInstanceId string                 `protobuf:"bytes,5,opt,name=masterInstanceId,proto3" json:"masterInstanceId,omitempty"`
	MaxOffset        int64                  `protobuf:"varint,6,opt,name=maxOffset,proto3" json:"maxOffset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SchedulerFileResponse) Reset() {
	*x = SchedulerFileResponse{}
	mi := &file_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerFileResponse) ProtoMessage() {}

func (x *SchedulerFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerFileResponse.ProtoReflect.Descriptor instead.
func (*SchedulerFileResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{4}
}

func (x *SchedulerFileResponse) GetSchedulerType() int32 {
	if x != nil {
		return x.SchedulerType
	}
	return 0
}

func (x *SchedulerFileResponse) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *SchedulerFileResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SchedulerFileResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SchedulerFileResponse) GetMasterInstanceId() string {
	if x != nil {
		return x.MasterInstanceId
	}
	return ""
}

func (x *SchedulerFileResponse) GetMaxOffset() int64 {
	if x != nil {
		return x.MaxOffset
	}
	return 0
}

type FileProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int64                  `protobuf:"varint,1,opt,name=processId,proto3" json:"processId,omitempty"`
	StaPos        int64                  `protobuf:"varint,2,opt,name=staPos,proto3" json:"staPos,omitempty"`
	EndPos        int64                  `protobuf:"varint,3,opt,name=endPos,proto3" json:"endPos,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileProcessRequest) Reset() {
	*x = FileProcessRequest{}
	mi := &file_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProcessRequest) ProtoMessage() {}

func (x *FileProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProcessRequest.ProtoReflect.Descriptor instead.
func (*FileProcessRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{5}
}

func (x *FileProcessRequest) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *FileProcessRequest) GetStaPos() int64 {
	if x != nil {
		return x.StaPos
	}
	return 0
}

func (x *FileProcessRequest) GetEndPos() int64 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *FileProcessRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteByEtagsAndFieldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Datatype      string                 `protobuf:"bytes,2,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Repo          string                 `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	InstanceID    string                 `protobuf:"bytes,6,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByEtagsAndFieldsRequest) Reset() {
	*x = DeleteByEtagsAndFieldsRequest{}
	mi := &file_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByEtagsAndFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByEtagsAndFieldsRequest) ProtoMessage() {}

func (x *DeleteByEtagsAndFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByEtagsAndFieldsRequest.ProtoReflect.Descriptor instead.
func (*DeleteByEtagsAndFieldsRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteByEtagsAndFieldsRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

var File_manager_proto protoreflect.FileDescriptor

const file_manager_proto_rawDesc = "" +
	"\n" +
	"\rmanager.proto\x12\amanager\x1a\x1bgoogle/protobuf/empty.proto\"q\n" +
	"\x0fRegisterRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\"<\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\"\n" +
	"\x10HeartbeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xf0\x01\n" +
	"\x14SchedulerFileRequest\x12\x1a\n" +
	"\bdataType\x18\x01 \x01(\tR\bdataType\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04etag\x18\x05 \x01(\tR\x04etag\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x06 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bstartPos\x18\a \x01(\x03R\bstartPos\x12\x16\n" +
	"\x06endPos\x18\b \x01(\x03R\x06endPos\x12\x1a\n" +
	"\bfileSize\x18\t \x01(\x03R\bfileSize\"\xcd\x01\n" +
	"\x15SchedulerFileResponse\x12$\n" +
	"\rschedulerType\x18\x01 \x01(\x05R\rschedulerType\x12\x1c\n" +
	"\tprocessId\x18\x02 \x01(\x03R\tprocessId\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12*\n" +
	"\x10masterInstanceId\x18\x05 \x01(\tR\x10masterInstanceId\x12\x1c\n" +
	"\tmaxOffset\x18\x06 \x01(\x03R\tmaxOffset\"z\n" +
	"\x12FileProcessRequest\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\x03R\tprocessId\x12\x16\n" +
	"\x06staPos\x18\x02 \x01(\x03R\x06staPos\x12\x16\n" +
	"\x06endPos\x18\x03 \x01(\x03R\x06endPos\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\xa9\x01\n" +
	"\x1dDeleteByEtagsAndFieldsRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12\x1a\n" +
	"\bdatatype\x18\x02 \x01(\tR\bdatatype\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x04 \x01(\tR\x04repo\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"instanceID\x18\x06 \x01(\tR\n" +
	"instanceID2\x80\x03\n" +
	"\aManager\x12A\n" +
	"\bRegister\x12\x18.manager.RegisterRequest\x1a\x19.manager.RegisterResponse\"\x00\x12>\n" +
	"\tHeartbeat\x12\x19.manager.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\rSchedulerFile\x12\x1d.manager.SchedulerFileRequest\x1a\x1e.manager.SchedulerFileResponse\x12H\n" +
	"\x11ReportFileProcess\x12\x1b.manager.FileProcessRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x16DeleteByEtagsAndFields\x12&.manager.DeleteByEtagsAndFieldsRequest\x1a\x16.google.protobuf.EmptyB\vZ\t.;managerb\x06proto3"

var (
	file_manager_proto_rawDescOnce sync.Once
	file_manager_proto_rawDescData []byte
)

func file_manager_proto_rawDescGZIP() []byte {
	file_manager_proto_rawDescOnce.Do(func() {
		file_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)))
	})
	return file_manager_proto_rawDescData
}

var file_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_manager_proto_goTypes = []any{
	(*RegisterRequest)(nil),               // 0: manager.RegisterRequest
	(*RegisterResponse)(nil),              // 1: manager.RegisterResponse
	(*HeartbeatRequest)(nil),              // 2: manager.HeartbeatRequest
	(*SchedulerFileRequest)(nil),          // 3: manager.SchedulerFileRequest
	(*SchedulerFileResponse)(nil),         // 4: manager.SchedulerFileResponse
	(*FileProcessRequest)(nil),            // 5: manager.FileProcessRequest
	(*DeleteByEtagsAndFieldsRequest)(nil), // 6: manager.DeleteByEtagsAndFieldsRequest
	(*emptypb.Empty)(nil),                 // 7: google.protobuf.Empty
}
var file_manager_proto_depIdxs = []int32{
	0, // 0: manager.Manager.Register:input_type -> manager.RegisterRequest
	2, // 1: manager.Manager.Heartbeat:input_type -> manager.HeartbeatRequest
	3, // 2: manager.Manager.SchedulerFile:input_type -> manager.SchedulerFileRequest
	5, // 3: manager.Manager.ReportFileProcess:input_type -> manager.FileProcessRequest
	6, // 4: manager.Manager.DeleteByEtagsAndFields:input_type -> manager.DeleteByEtagsAndFieldsRequest
	1, // 5: manager.Manager.Register:output_type -> manager.RegisterResponse
	7, // 6: manager.Manager.Heartbeat:output_type -> google.protobuf.Empty
	4, // 7: manager.Manager.SchedulerFile:output_type -> manager.SchedulerFileResponse
	7, // 8: manager.Manager.ReportFileProcess:output_type -> google.protobuf.Empty
	7, // 9: manager.Manager.DeleteByEtagsAndFields:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_manager_proto_init() }
func file_manager_proto_init() {
	if File_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_proto_goTypes,
		DependencyIndexes: file_manager_proto_depIdxs,
		MessageInfos:      file_manager_proto_msgTypes,
	}.Build()
	File_manager_proto = out.File
	file_manager_proto_goTypes = nil
	file_manager_proto_depIdxs = nil
}
